### ISSUE TITLE
Optimize image already reduced can produce a bigger file

### ISSUE THREAD

**Issue by davddo** [globalis-ms/wp-cubi-imagemin#8]
[25/51] Optimize image: [...]/image.png : -103 B were saved (-13%)

Example :
![googleplus](https://user-images.githubusercontent.com/5182811/39366630-c2db7718-4a34-11e8-8703-7ed81f7d3ced.png)

**Comment by pierre-dargham** [comment]
Closed by https://github.com/globalis-ms/wp-cubi-imagemin/pull/11
